# Build Geth in a stock Go builder container
FROM golang:1.14-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git

ADD . /go-ethersocial
RUN cd /go-ethersocial && make all

# Pull all binaries into a second stage deploy alpine container
FROM alpine:latest

RUN apk add --no-cache ca-certificates
COPY --from=builder /go-ethersocial/build/bin/* /usr/local/bin/

EXPOSE 9545 9546 9547 50505 50505/udp
